# Generated by Django 2.2.28 on 2025-01-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrobascula',
            options={'verbose_name': 'Registro de Báscula', 'verbose_name_plural': 'Registros de Báscula'},
        ),
        migrations.AlterModelOptions(
            name='registrodispositivo',
            options={'verbose_name': 'Registro de Dispositivo', 'verbose_name_plural': 'Registros de Dispositivo'},
        ),
    ]
